"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 11:04:47.096196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('sex', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('address_line_1', sa.String(length=200), nullable=False),
    sa.Column('address_line_2', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('zip_code', sa.String(length=10), nullable=False),
    sa.Column('insurance_provider', sa.String(length=100), nullable=True),
    sa.Column('insurance_member_id', sa.String(length=50), nullable=True),
    sa.Column('preferred_language', sa.String(length=50), server_default='English', nullable=False),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("sex IN ('Male','Female','Other','Decline to Answer')", name='ck_patients_sex'),
    sa.CheckConstraint('emergency_contact_phone IS NULL OR length(emergency_contact_phone) = 10', name='ck_patients_ec_phone_len'),
    sa.CheckConstraint('length(first_name) >= 1 AND length(last_name) >= 1', name='ck_patients_name_nonempty'),
    sa.CheckConstraint('length(phone_number) = 10', name='ck_patients_phone_len'),
    sa.CheckConstraint('length(state) = 2', name='ck_patients_state_len'),
    sa.PrimaryKeyConstraint('patient_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index('ix_patients_date_of_birth', ['date_of_birth'], unique=False)
        batch_op.create_index('ix_patients_last_name', ['last_name'], unique=False)
        batch_op.create_index('ix_patients_phone_number', ['phone_number'], unique=False)

    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('vapi_call_id', sa.String(length=100), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('caller_number', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('ended_reason', sa.String(length=100), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vapi_call_id')
    )
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_call_logs_patient_id'), ['patient_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_call_logs_patient_id'))

    op.drop_table('call_logs')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index('ix_patients_phone_number')
        batch_op.drop_index('ix_patients_last_name')
        batch_op.drop_index('ix_patients_date_of_birth')

    op.drop_table('patients')
    # ### end Alembic commands ###
